name: trendy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  agora_rtc_engine: ^6.2.2
  agora_rtm: ^1.5.0
  permission_handler: ^11.0.0
  countup: ^0.1.4
  video_player: ^2.4.5
  lottie: ^2.3.2
  qr_flutter: ^4.0.0
  pro_image_editor: ^10.5.4
  cupertino_icons: ^1.0.8
  audioplayers: ^5.2.1
  firebase_core: ^2.32.0
  firebase_auth: ^4.11.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.6.5
  firebase_messaging: ^14.7.0
  firebase_performance: ^0.9.4+7
  provider: ^6.1.2
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  vibration: ^1.8.4
  flutter_sound: ^9.2.13
  web_socket_channel: ^2.4.0
  connectivity_plus: ^5.0.2
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  google_mobile_ads: ^3.1.0
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^7.1.2
  sign_in_with_apple: ^4.2.1
  flutter_dotenv: ^5.1.0
  email_validator: ^2.1.17
  logger: ^1.0.0  # Added logger package

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
