// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb-0MsyxpID3b8WRAyiDwDlgY19TUETEg',
    appId: '1:818367989466:web:your-web-app-id',
    messagingSenderId: '818367989466',
    projectId: 'trendy-83364',
    authDomain: 'trendy-83364.firebaseapp.com',
    storageBucket: 'trendy-83364.firebasestorage.app',
    measurementId: 'G-YOUR-MEASUREMENT-ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb-0MsyxpID3b8WRAyiDwDlgY19TUETEg',
    appId: '1:818367989466:android:1de8d15f17ac11f7d9c7e3',
    messagingSenderId: '818367989466',
    projectId: 'trendy-83364',
    storageBucket: 'trendy-83364.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb-0MsyxpID3b8WRAyiDwDlgY19TUETEg',
    appId: '1:818367989466:ios:your-ios-app-id',
    messagingSenderId: '818367989466',
    projectId: 'trendy-83364',
    storageBucket: 'trendy-83364.firebasestorage.app',
    iosBundleId: 'com.vibe.trendy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb-0MsyxpID3b8WRAyiDwDlgY19TUETEg',
    appId: '1:818367989466:macos:your-macos-app-id',
    messagingSenderId: '818367989466',
    projectId: 'trendy-83364',
    storageBucket: 'trendy-83364.firebasestorage.app',
    iosBundleId: 'com.vibe.trendy',
  );
}
